TARGET = SDL2dcSemaphoreTest
 
# Update include paths for SDL2
KOS_CFLAGS+= -I../../../../build-scripts/build/include -I../../../../build-scripts/build/include-config-/SDL2 -I../../../../build-scripts/build/include/SDL2 -I. -DDREAMCAST

# Update library paths and libraries for SDL2
KOS_LIBS+= -L../../../../build-scripts/build -lSDL2 -lSDL2main

all: $(TARGET).bin

include $(KOS_BASE)/Makefile.rules 

OBJS =	testsem.o #romdisk.o

clean:
	rm -f $(OBJS) $(TARGET).elf $(TARGET).bin romdisk.o romdisk.img

$(TARGET).elf: $(OBJS) 
	$(KOS_CC) $(KOS_CFLAGS) $(KOS_LDFLAGS) -o $(TARGET).elf $(KOS_START) \
	$(OBJS) $(OBJEXTRA) -lSDL2 -lSDL2main -lGL -lm -lkosutils $(KOS_LIBS)

$(TARGET).bin: $(TARGET).elf
	$(KOS_OBJCOPY) -R .stack -O binary $(TARGET).elf $(TARGET).bin

romdisk.o: romdisk.img
	$(KOS_BASE)/utils/bin2o/bin2o romdisk.img romdisk romdisk.o
#	bin2odc romdisk.img romdisk.o

romdisk.img: data
	$(KOS_GENROMFS) -f romdisk.img -d data -v

run: $(TARGET).bin 
	$(KOS_LOADER) $(TARGET).bin
